# Day 4

## Iteration of Arrays

In [1]:
## list iteraion
L=[10,20,30,40]

In [2]:
for i in L:             ## method - 1   using element
    print(i)       

10
20
30
40


In [3]:
for i in range(len(L)):               ## method - 2   using index
    print(L[i])

10
20
30
40


## Iteration for 1D array

In [6]:
import numpy as np
a = np.array([100,201,32,5,45,52])
a

array([100, 201,  32,   5,  45,  52])

In [7]:
for i in a:
    print(i,end=" ")

100 201 32 5 45 52 

## Iteration for 2D array

In [8]:
b = a.reshape(2,3)   ## creating 2d using 1d array by reshaping
b

array([[100, 201,  32],
       [  5,  45,  52]])

In [9]:
for i in b:
    for j in i:
        print(j,end=" ")

100 201 32 5 45 52 

## Iteration for 3D array

In [10]:
c = a.reshape(2,3,1)   ## creating 3d using 1d array by reshaping
c

array([[[100],
        [201],
        [ 32]],

       [[  5],
        [ 45],
        [ 52]]])

In [11]:
for i in c:
    for j in i:
        for k in j:
            print(k,end=" ")

100 201 32 5 45 52 

## keyword for iterating the array - np.nditer

In [12]:
for i in np.nditer(c):
    print(i,end=" ")

100 201 32 5 45 52 

In [13]:
help(np.nditer)

Help on class nditer in module numpy:

class nditer(builtins.object)
 |  nditer(op, flags=None, op_flags=None, op_dtypes=None, order='K', casting='safe', op_axes=None, itershape=None, buffersize=0)
 |  
 |  Efficient multi-dimensional iterator object to iterate over arrays.
 |  To get started using this object, see the
 |  :ref:`introductory guide to array iteration <arrays.nditer>`.
 |  
 |  Parameters
 |  ----------
 |  op : ndarray or sequence of array_like
 |      The array(s) to iterate over.
 |  
 |  flags : sequence of str, optional
 |        Flags to control the behavior of the iterator.
 |  
 |        * ``buffered`` enables buffering when required.
 |        * ``c_index`` causes a C-order index to be tracked.
 |        * ``f_index`` causes a Fortran-order index to be tracked.
 |        * ``multi_index`` causes a multi-index, or a tuple of indices
 |          with one per iteration dimension, to be tracked.
 |        * ``common_dtype`` causes all the operands to be converted to

## Joining of an array
* To concatenate any 2 arrays the shape and dimensions should be same

In [15]:
a = np.arange(1,5)     ## 1-D array
b = np.arange(11,20)
print(a,end=" ")
print(b,end=" ")

[1 2 3 4] [11 12 13 14 15 16 17 18 19] 

In [16]:
c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
## 2D array

c = a.reshape(2,2)
d = b.reshape(3,3)
e = np.concatenate((c,d))

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

In [18]:
a = np.arange(1,5)    
b = np.arange(6,10)
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [20]:
c = a.reshape(2,2)
d = b.reshape(2,2)
print(c)
print(d)
e = np.concatenate((c,d))
e

[[1 2]
 [3 4]]
[[6 7]
 [8 9]]


array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [22]:
## 3d array
f = a.reshape(2,1,2)
g = b.reshape(2,1,2)
print(f)
print(g)
h = np.concatenate((f,g))
h

[[[1 2]]

 [[3 4]]]
[[[6 7]]

 [[8 9]]]


array([[[1, 2]],

       [[3, 4]],

       [[6, 7]],

       [[8, 9]]])

## Statistical and Math operations of an arrays

In [106]:
a = np.arange(1,5)    
b = np.arange(6,10)
c = np.concatenate((a,b))
c

array([1, 2, 3, 4, 6, 7, 8, 9])

In [107]:
np.min(c)

1

In [108]:
np.max(c)

9

In [110]:
a = np.array([[1,2,3],[0,9,4]])
a

array([[1, 2, 3],
       [0, 9, 4]])

In [111]:
np.min(a)

0

In [112]:
np.max(a)

9

### argmin ---- it gives the min index of an array

In [113]:
a.argmin()

3

### argmax ---- it gives the max index of an array

In [114]:
a.argmax()

4

In [115]:
d

array([[6, 7],
       [8, 9]])

In [116]:
d.argmin()

0

In [117]:
d.argmax()

3

In [119]:
help(c.argmin)

Help on built-in function argmin:

argmin(...) method of numpy.ndarray instance
    a.argmin(axis=None, out=None)
    
    Return indices of the minimum values along the given axis of `a`.
    
    Refer to `numpy.argmin` for detailed documentation.
    
    See Also
    --------
    numpy.argmin : equivalent function



In [120]:
help(c.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [24]:
c.mean()

2.5

In [25]:
c.median()   ## error

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [27]:
np.median(c)

2.5

In [28]:
np.var(c)  ##variance

1.25

In [29]:
np.average(c)

2.5

In [30]:
np.std(c)  ##standard deviation

1.118033988749895

In [31]:
np.mode(c)   ##error

AttributeError: module 'numpy' has no attribute 'mode'

In [32]:
## sum of the elements of the array
np.sum(c)

10

In [33]:
## sum of row elements
np.sum(c,1)   #1-row , 0-column

array([3, 7])

In [34]:
np.sum(c,0)  ## sum of coloumn elements

array([4, 6])

## stacking:
* arranging/organising in an appropriate way
* horizontal stacking
* vertical stacking

In [35]:
c

array([[1, 2],
       [3, 4]])

In [36]:
np.hstack(c)

array([1, 2, 3, 4])

In [37]:
np.vstack(c)

array([[1, 2],
       [3, 4]])

In [38]:
d

array([[6, 7],
       [8, 9]])

In [41]:
np.vstack((c,d))

array([[1, 2],
       [3, 4],
       [6, 7],
       [8, 9]])

In [42]:
print(*c)

[1 2] [3 4]


In [43]:
g

array([[[6, 7]],

       [[8, 9]]])

In [44]:
np.hstack(g)

array([[6, 7, 8, 9]])

In [45]:
h=np.array([[[65,78]],[[54,32]]])

In [46]:
np.vstack((g,h))

array([[[ 6,  7]],

       [[ 8,  9]],

       [[65, 78]],

       [[54, 32]]])

In [47]:
c

array([[1, 2],
       [3, 4]])

In [48]:
np.sqrt(c)   ##square root of array element

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [49]:
np.exp(c)  ##exponent of  array elements

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [50]:
np.sin(c)  ##sine of an elements

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [51]:
np.cos(c)  ##cos of an elements

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [52]:
np.tan(c)  ##tan of an elements

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

In [53]:
np.log(c)  ##logarthmic values of the array

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [54]:
np.log2(c) ## log values with base 2

array([[0.       , 1.       ],
       [1.5849625, 2.       ]])

In [55]:
np.log10(c)  ##log values base with 10

array([[0.        , 0.30103   ],
       [0.47712125, 0.60205999]])

In [56]:
np.power(c,2)   ## squre of an elements

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [57]:
np.power(c,3)  ##cube of an elements

array([[ 1,  8],
       [27, 64]], dtype=int32)

In [58]:
c

array([[1, 2],
       [3, 4]])

In [59]:
np.remainder(c,3)  #remainder of each array elements

array([[1, 2],
       [0, 1]], dtype=int32)

In [60]:
np.degrees(c)  ##degres of array elements

array([[ 57.29577951, 114.59155903],
       [171.88733854, 229.18311805]])

In [61]:
help(np.degrees)

Help on ufunc object:

degrees = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  Calling ufuncs:
 |  ===============
 |  
 |  op(*x[, out], where=True, **kwargs)
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate arr

In [62]:
c

array([[1, 2],
       [3, 4]])

In [63]:
##  diff
np.diff(c)  ##row wisw diff by default


array([[1],
       [1]])

In [64]:
np.diff(c,axis=0)  ## column wise

array([[2, 2]])

In [65]:
np.ediff1d(c)  ## converts given array into id array and  [1 2 3 4]
                ## calculates the consecutive diff of the each element

array([1, 1, 1])

In [66]:
np.mod(c,4)  ## modulous of each element in the array

array([[1, 2],
       [3, 0]], dtype=int32)

In [67]:
np.multiply(c,100)  # product of array elements with a given number

array([[100, 200],
       [300, 400]])

In [68]:
np.divide(c,2)

array([[0.5, 1. ],
       [1.5, 2. ]])

In [69]:
a = np.array([1+2j,9+4j,8+5j])
a

array([1.+2.j, 9.+4.j, 8.+5.j])

In [70]:
np.real(a)  ## real values of given array elements

array([1., 9., 8.])

In [71]:
np.imag(a)  ## imaginary values of given array

array([2., 4., 5.])

## Ravel and Flatten:
* Ravel : 
    - it is a function used to create a copy of the original array when any changes made in the duplicate array those will also applied in original array.
* Flatten :  
    - it is a function used to create a copy of the original array when any changes made in the duplicate array will not be applied in original array.

In [73]:
original = np.arange(1,10)
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
copy = original.ravel()
copy

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
copy[0] = 110

In [76]:
copy

array([110,   2,   3,   4,   5,   6,   7,   8,   9])

In [77]:
original

array([110,   2,   3,   4,   5,   6,   7,   8,   9])

In [79]:
original1 = np.arange(10,20)
original1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [84]:
copy = original1.flatten()
copy

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [85]:
copy[2]=3000

In [86]:
copy

array([  10,   11, 3000,   13,   14,   15,   16,   17,   18,   19])

In [87]:
original1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [88]:
dir(np.math)

['__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 'acos',
 'acosh',
 'asin',
 'asinh',
 'atan',
 'atan2',
 'atanh',
 'ceil',
 'comb',
 'copysign',
 'cos',
 'cosh',
 'degrees',
 'dist',
 'e',
 'erf',
 'erfc',
 'exp',
 'expm1',
 'fabs',
 'factorial',
 'floor',
 'fmod',
 'frexp',
 'fsum',
 'gamma',
 'gcd',
 'hypot',
 'inf',
 'isclose',
 'isfinite',
 'isinf',
 'isnan',
 'isqrt',
 'ldexp',
 'lgamma',
 'log',
 'log10',
 'log1p',
 'log2',
 'modf',
 'nan',
 'perm',
 'pi',
 'pow',
 'prod',
 'radians',
 'remainder',
 'sin',
 'sinh',
 'sqrt',
 'tan',
 'tanh',
 'tau',
 'trunc']

In [91]:
np.reciprocal(c)

array([[1, 0],
       [0, 0]], dtype=int32)

In [92]:
np.ceil(c)

array([[1., 2.],
       [3., 4.]])

In [93]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [94]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [96]:
help(np.math.factorial)

Help on built-in function factorial in module math:

factorial(x, /)
    Find x!.
    
    Raise a ValueError if x is negative or non-integral.



In [98]:
np.math.factorial(5)

120

In [100]:
a=np.array([10,4,14])
a

array([10,  4, 14])

In [101]:
np.math.factorial(a[1])

24

In [102]:
np.math.factorial(a) ## error

TypeError: only integer scalar arrays can be converted to a scalar index