## DAY 3
### NUMPY
* Numpy stands for numerical python.
* It is a python library used to work with arrays.
* It also has functions work with linear alzebra,fourier transformer, matrices etc....
*  Array object here is called n dimentional array.
* Ndarray is 5x faster than lists in python.

### Importing the library numpy syntax
### install numpy - pip install numpy

In [1]:
import numpy ## method 1.

In [2]:
import numpy as np ## method 2 insted of numpy  we use np.

### Creating an Array - 1 Dimentional array

In [4]:
a = np.array([10,20,30,40,50,60,])
a

array([10, 20, 30, 40, 50, 60])

In [5]:
type(a)

numpy.ndarray

### To find no.od domentions od array

In [6]:
a.ndim

1

### Data type of an array

In [7]:
a.dtype

dtype('int32')

### Shape of an array

In [8]:
a.shape

(6,)

### Size of an array

In [9]:
a.size

6

### Each Item size of an array in bytes

In [10]:
a.itemsize

4

In [11]:
a=np.array([1,2,3,4],np.int8)

In [12]:
a

array([1, 2, 3, 4], dtype=int8)

In [13]:
2**8-1  ## no of dtype

255

In [14]:
a=np.array([1,2,3,4,512],np.int8)
a

array([1, 2, 3, 4, 0], dtype=int8)

### Float

In [15]:
ar= np.array([10,20,30,64.2])
print(ar)
print(ar.dtype)

[10.  20.  30.  64.2]
float64


### String

In [17]:
b = np.array([100,85,44,'Meghana'])
print(b)

['100' '85' '44' 'Meghana']


In [18]:
dir(np.dtype)

['__bool__',
 '__class__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmul__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'alignment',
 'base',
 'byteorder',
 'char',
 'descr',
 'fields',
 'flags',
 'hasobject',
 'isalignedstruct',
 'isbuiltin',
 'isnative',
 'itemsize',
 'kind',
 'metadata',
 'name',
 'names',
 'ndim',
 'newbyteorder',
 'num',
 'shape',
 'str',
 'subdtype',
 'type']

### appendig single element to an array

In [19]:
c=np.array([9,8,90])
c

array([ 9,  8, 90])

In [21]:
c = np.append(c,20)
c

array([ 9,  8, 90, 20])

### appendig multiple elements to an array

In [22]:
c=np.append(c,[200,100,300])
c

array([  9,   8,  90,  20, 200, 100, 300])

### creating ndarray using range()

In [23]:
r = np.array(range(9))
print(r)
print(type(r))

[0 1 2 3 4 5 6 7 8]
<class 'numpy.ndarray'>


In [24]:
r = np.array(range(1,9,2))  ## start,stop,step
print(r)
print(type(r))

[1 3 5 7]
<class 'numpy.ndarray'>


### Creating ndarray using list

In [26]:
l=[20,30,50,40,60]
a=np.array(1)
print(a)
print(type(a))

1
<class 'numpy.ndarray'>


### Creating ndarray using arrange() function

In [27]:
a = np.arange(1,11)  #range of values
print(a)
print(type(a))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [28]:
a = np.arange(1,11,2)  #range of values with step values
print(a)
print(type(a))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [29]:
a.nbytes ## checks the memory space occupied by array

20

In [30]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [31]:
print(len(a))   ## length od array
print(a.itemsize) ## checks each element size

5
4


In [33]:
print(np.arange(11,21))
print(np.arange(5))
print(np.arange(4,1))  ## reverse not works this statement

[11 12 13 14 15 16 17 18 19 20]
[0 1 2 3 4]
[]


### Creating array using linspace

In [34]:
a = np.linspace(1,10,20)  ## start,stop,no.of elements  creating required no.of elements
a

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

### Creating array using logspace

In [36]:
a = np.logspace(1,10,20)  ## returns log values of given range
a

array([1.00000000e+01, 2.97635144e+01, 8.85866790e+01, 2.63665090e+02,
       7.84759970e+02, 2.33572147e+03, 6.95192796e+03, 2.06913808e+04,
       6.15848211e+04, 1.83298071e+05, 5.45559478e+05, 1.62377674e+06,
       4.83293024e+06, 1.43844989e+07, 4.28133240e+07, 1.27427499e+08,
       3.79269019e+08, 1.12883789e+09, 3.35981829e+09, 1.00000000e+10])

In [37]:
np.full(10,"maggi")   ## repeting required no.of times and making into array.

array(['maggi', 'maggi', 'maggi', 'maggi', 'maggi', 'maggi', 'maggi',
       'maggi', 'maggi', 'maggi'], dtype='<U5')

In [38]:
np.full(10,"1 2")

array(['1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2', '1 2',
       '1 2'], dtype='<U3')

In [39]:
np.ones(10)   ## repeting ones for required no.of times and making into array.

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [40]:
np.ones(10,dtype=int)  

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [41]:
np.zeros(10,dtype=int) ## repeting zeros with defined no.of times

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Creating 2D array

In [42]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)
print(type(a))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
<class 'numpy.ndarray'>


In [43]:
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

2
int32
48
4


### 3D array : Combination of meor no of 2-d arrays

In [44]:
a = np.array([[[9,8,7],[6,5,4]], [[1,2,3],[30,20,10]]])
a

array([[[ 9,  8,  7],
        [ 6,  5,  4]],

       [[ 1,  2,  3],
        [30, 20, 10]]])

In [45]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

<class 'numpy.ndarray'>
3
int32
48
4


## Multi D array

In [47]:
a = np.array([9,8,7,6,5,4],ndmin=20)
a

array([[[[[[[[[[[[[[[[[[[[9, 8, 7, 6, 5, 4]]]]]]]]]]]]]]]]]]]])

In [48]:
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.nbytes)
print(a.itemsize)

<class 'numpy.ndarray'>
20
int32
24
4


### Accessing elements from an array
### For 1D array

In [49]:
a = np.array([10,202,30,40,50,600])
a

array([ 10, 202,  30,  40,  50, 600])

### forward index ---> starts from zero
### Backward indexing ---> starts from -1 from backside

In [50]:
a[3]

40

In [51]:
a[-3]

40

In [52]:
a[-5]

202

In [53]:
a

array([ 10, 202,  30,  40,  50, 600])

In [54]:
## print - 202 30 40

a[1:4]

array([202,  30,  40])

In [55]:
a[::-1]  ## reverse order

array([600,  50,  40,  30, 202,  10])

### For 2D array

In [56]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
b.size

8

In [58]:
b.shape

(2, 4)

In [59]:
b[0]  ## 1st row

array([1, 2, 3, 4])

In [60]:
b[1]  ## 2nd row

array([5, 6, 7, 8])

In [61]:
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [62]:
b[1,2]  ##accessing a particular element by using row, column index

7

In [63]:
b[0][0]

1

In [64]:
b[:,0] ## 1st column

array([1, 5])

In [65]:
b[:,-2]

array([3, 7])

In [66]:
b[:,-2:]  ##row index slicing,element index slicing

array([[3, 4],
       [7, 8]])

In [67]:
b[:,1:3]

array([[2, 3],
       [6, 7]])

## For 3D array

In [68]:
c = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])
c

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[10, 20, 30, 40],
        [50, 60, 70, 80]]])

In [71]:
c[0]   #2-d index

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [72]:
c[1]

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [73]:
c[0,0]

array([1, 2, 3, 4])

In [74]:
c[0,1]

array([5, 6, 7, 8])

In [75]:
c[1,1]

array([50, 60, 70, 80])

In [76]:
c[1,0]

array([10, 20, 30, 40])

In [77]:
c[1,1,2]

70

In [78]:
c[1,0,2]

30

In [80]:
c[0,0,-2]

3

In [81]:
c[:,0,-1]  ## 0th column, -1 element

array([ 4, 40])

In [82]:
c[1,0,-1]

40

### shape of an array

In [83]:
a=np.array([4,5,6])
a.shape

(3,)

In [84]:
b=np.array([[4,5,6],[1,2,3]])
b.shape

(2, 3)

In [86]:
c=np.array([[[4,5],[1,2]],[[3,4],[5,6]]])
c.shape

(2, 2, 2)

### Reshaping of an array

In [88]:
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [89]:
b = a.reshape(4,5)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [90]:
b.ndim

2

In [91]:
a.reshape(5,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [92]:
a.reshape(2,10)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20]])

In [93]:
a.reshape(10,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [94]:
a.reshape(2,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [95]:
a.reshape(2,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [96]:
a.reshape(1,19)

ValueError: cannot reshape array of size 20 into shape (1,19)

In [97]:
a.reshape(4,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [98]:
a.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [99]:
a.reshape(-1,2,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]]])

In [100]:
a=np.arange(1,11).reshape(5,2)
a

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Create using numpy with all dimensions