# DAY 5
## Random methods

In [1]:
import numpy as np

## Randint function

In [2]:
np.random.randint(140)  ## integer value within a given range

31

## Rand function

In [3]:
np.random.rand()   ## print float values within 0 and 1 range

0.40860116877071695

## Randint function
* 1D Array with defines no of elements and size

In [4]:
np.random.randint(100,size=(20))

array([38, 36, 68, 51, 54, 65, 23, 10, 15, 93, 37, 12, 23, 97, 33, 77, 33,
       96, 73, 77])

* 2D Array

In [7]:
np.random.randint(50,size=(2,3))

array([[23, 38,  0],
       [10, 30, 18]])

* 3D Array

In [9]:
np.random.randint(50,size=(2,3,1))

array([[[31],
        [42],
        [44]],

       [[10],
        [33],
        [28]]])

## Choice function
* Returns the random choice of given elements

* 1D ARRAY

In [12]:
np.random.choice([1,2,3,5,8,10])

2

* 2D Array

In [13]:
np.random.choice([10,20,30,40,50,60],size=(3,2))

array([[40, 10],
       [20, 50],
       [50, 30]])

* 3D Array

In [14]:
np.random.choice([10,20,30,40,50,60],size=(3,2,2))

array([[[20, 10],
        [40, 60]],

       [[50, 20],
        [20, 30]],

       [[20, 30],
        [60, 10]]])

## Randn function
* Gives both +ve and -ve values in defined number

In [15]:
np.random.randn(20)

array([-1.67171097,  3.12208856,  1.36256135, -0.62454479,  0.04320193,
        1.17983588,  0.87823018, -0.13088856,  0.68883133,  0.06632726,
       -0.69511103,  0.96186617, -0.8572623 ,  0.86948505,  1.28919589,
       -0.38675127, -0.82003892, -0.8416383 ,  0.26156448,  0.77864833])

## Normal distribution value

In [16]:
np.random.normal()

0.24170348124795013

## Array Filtering
*  filtering function will returns based on bulian values which are true only.

In [20]:
a = np.array([90,89,78,88,20])
b = [False,True,True,True,False]
c = a[b]

In [21]:
c

array([89, 78, 88])

* Print values greater than 20 in the given array below
* a = np.array([90,89,78,88,20])

In [22]:
b = []   ## b=[True,true,true,true,false]
for i in a:
    if i>20:
        b.append(True)
    else:
        b.append(False)
c = a[b]
c

array([90, 89, 78, 88])

In [23]:
## another method
d = a>20
e = a[d]
e

array([90, 89, 78, 88])

In [25]:
a.reshape(5,1)

array([[90],
       [89],
       [78],
       [88],
       [20]])

* Transpose of array

In [26]:
a.T

array([90, 89, 78, 88, 20])

In [27]:
e

array([90, 89, 78, 88])

# Pandas
* pandas is a built in library using data analysis.
* Used for Data manipulations,visualisations,building ML models.
* There are two main data structures in pands
    - Series and DataFrames.

In [28]:
import pandas as pd

* To know the current version of pands

In [29]:
pd.__version__

'1.0.5'

## Pandas

* A series is similar to a 1D array and contains values of same type.
* Data frame is simply a table where each column is a pandas series.

### Series

* Creating Series
    - List
    - Tuple
    - Dictionary
    - Numpy
    - Date_range
    - series indexing

### Creating pands using list

In [31]:
L = [80,7,90,60,5,85] 
p = pd.Series(L)
p

0    80
1     7
2    90
3    60
4     5
5    85
dtype: int64

### Creating Pandas using tuple

In [32]:
T = (89,56,47,25)
s = pd.Series(T)
s

0    89
1    56
2    47
3    25
dtype: int64

In [33]:
P1 = pd.Series(T,index=['A','B','C','D'])
P1

A    89
B    56
C    47
D    25
dtype: int64

### Creating series with Dictionary

In [35]:
D = {'maggi':56,'dinu':47,'camel':85,'dog':78,'egg':56}
s = pd.Series(D)
s

maggi    56
dinu     47
camel    85
dog      78
egg      56
dtype: int64

In [36]:
s.index=[10,'a','b','c','d']  ## Reindexing
s

10    56
a     47
b     85
c     78
d     56
dtype: int64

In [37]:
s['d']   ## getting values using index

56

In [38]:
s[10]

56

In [39]:
s[1:3]   ## START AND STOP  VALUES

a    47
b    85
dtype: int64

In [40]:
s

10    56
a     47
b     85
c     78
d     56
dtype: int64

In [41]:
s[1:4:2]  # start,stop,step

a    47
c    78
dtype: int64

In [42]:
s

10    56
a     47
b     85
c     78
d     56
dtype: int64

In [43]:
s.index = np.arange(30,35)
s

30    56
31    47
32    85
33    78
34    56
dtype: int64

In [45]:
s = pd.Series("MEGHANA",index=[1,2,3,4])

In [46]:
s

1    MEGHANA
2    MEGHANA
3    MEGHANA
4    MEGHANA
dtype: object

### Power 
* Creat a series object having power of index value
    * 1 ---- 1  
    * 2 ----- 4  
    * 3 ----- 9
          '
          '
          '
          '
          '
          '
          '
    * 10 --- 100

In [47]:
s = pd.Series([i**2 for i in range(11)])
s

0       0
1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
dtype: int64

* Squares of n natural numbers

In [49]:
n=int(input())
s = pd.Series([i**2 for i in range(1,n+1)],index=list(range(1,n+1)))
s

20


1       1
2       4
3       9
4      16
5      25
6      36
7      49
8      64
9      81
10    100
11    121
12    144
13    169
14    196
15    225
16    256
17    289
18    324
19    361
20    400
dtype: int64

### Power Using Dictionary Comprehension

In [50]:
n = int(input())
d = {i:i**2 for i in range(1,n+1)}
p = pd.Series(d)
p

5


1     1
2     4
3     9
4    16
5    25
dtype: int64

In [54]:
## another method
s = pd.Series(np.square(np.arange(1,10)))
s.index = [1,2,3,4,5,6,7,8,9]
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

In [55]:
s.index=range(1,10)

In [56]:
s

1     1
2     4
3     9
4    16
5    25
6    36
7    49
8    64
9    81
dtype: int32

### Date Range Method

In [57]:
Dates = pd.date_range(start="2020-10-5",end="2020-10-12")
Dates

DatetimeIndex(['2020-10-05', '2020-10-06', '2020-10-07', '2020-10-08',
               '2020-10-09', '2020-10-10', '2020-10-11', '2020-10-12'],
              dtype='datetime64[ns]', freq='D')

In [58]:
help(pd.date_range)

Help on function date_range in module pandas.core.indexes.datetimes:

date_range(start=None, end=None, periods=None, freq=None, tz=None, normalize=False, name=None, closed=None, **kwargs) -> pandas.core.indexes.datetimes.DatetimeIndex
    Return a fixed frequency DatetimeIndex.
    
    Parameters
    ----------
    start : str or datetime-like, optional
        Left bound for generating dates.
    end : str or datetime-like, optional
        Right bound for generating dates.
    periods : int, optional
        Number of periods to generate.
    freq : str or DateOffset, default 'D'
        Frequency strings can have multiples, e.g. '5H'. See
        :ref:`here <timeseries.offset_aliases>` for a list of
        frequency aliases.
    tz : str or tzinfo, optional
        Time zone name for returning localized DatetimeIndex, for example
        'Asia/Hong_Kong'. By default, the resulting DatetimeIndex is
        timezone-naive.
    normalize : bool, default False
        Normalize start/

### Creating series by using numpy array

In [59]:
n = np.arange(10)
n

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
s = pd.Series(n,index=np.arange(1,11))
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [63]:
n1 = np.array([20,21,5,22,54])
n1

array([20, 21,  5, 22, 54])

In [64]:
s1 = pd.Series(n1)
s1

0    20
1    21
2     5
3    22
4    54
dtype: int32

In [66]:
s2 = pd.Series(np.array([90,89,89,88]),index = ['p','q','r','s'])
s2

p    90
q    89
r    89
s    88
dtype: int32

In [67]:
s

1     0
2     1
3     2
4     3
5     4
6     5
7     6
8     7
9     8
10    9
dtype: int32

In [68]:
s[0:2]

1    0
2    1
dtype: int32

In [69]:
s[0:11:2]

1    0
3    2
5    4
7    6
9    8
dtype: int32

### Fancy Indexing

In [71]:
s[[7,8,9]]

7    6
8    7
9    8
dtype: int32

In [72]:
d = {"A":45,"B":54,"C":87,"D":np.nan,"E":"maggi"}
q = pd.Series(d)
q

A       45
B       54
C       87
D      NaN
E    maggi
dtype: object

In [74]:
q["D"]   ##assing value to a nan value

nan

In [75]:
q["D"]="ROSE"

In [77]:
q

A       45
B       54
C       87
D     ROSE
E    maggi
dtype: object